### ISSUE TITLE
define resolution of camera snapshot?

### ISSUE THREAD

**Issue by dougollerenshaw** [tchellomello/python-amcrest#119]
Thanks for this package! Is it possible to set the resolution when requesting a camera snapshot? 

https://github.com/tchellomello/python-amcrest/blob/2598f134900621c32499ea33e5a8d6c47dc9c593/examples/get-snapshot.py#L19

I'm getting much lower resolution images than I do if I click the 'snapshot' icon in the web UI, so I know the cameras are capable of more.

**Comment by pnbruckner** [comment]
No, the API does not allow selecting between the main stream and the extra stream. It only uses the main stream. I just compared a picture taken via the snapshot method of this package and the Amcrest Web app, and they're the same. Not sure why you would have seen different resolutions. Are you sure they are, or are the files just different sizes? Different file sizes do not necessary mean different resolution.
