### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'verify'

### ISSUE THREAD

**Issue by dev4488** [tchellomello/python-amcrest#126]
Getting this issue while accessing the camera. Anybody else seen this? 
Would appreciate any help!

camera = AmcrestCamera('192.168.0.1', 80, 'admin', 'passd').camera
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaconda3/lib/python3.7/site-packages/amcrest/__init__.py", line 33, in __init__
    timeout_protocol=timeout_protocol
TypeError: __init__() got an unexpected keyword argument 'verify'

**Comment by mehdilauters** [comment]
I've got the same issue
This is because the argument is called `ssl_verify` and not `verify` [there](https://github.com/tchellomello/python-amcrest/blob/master/src/amcrest/http.py#L48)
The workaround is to rename it...

**Comment by dev4488** [comment]
It works, thanks!
