### ISSUE TITLE
Trigger Motion Detection Event via API

### ISSUE THREAD

**Issue by NickWaterton** [tchellomello/python-amcrest#139]
Does anyone know how to trigger a motion detection event via the API?

The problem I have is that the camera reacts to lights turning on as if they were motion. I have the camera recording 24/7 (ie scheduled), and when motion is detected, it records that motion flagged as motion (ie stupid file name with '[M]' in it in place of '[R]').

This works fine, but is constantly recording the hallway light turning on and off.
I also use `motion` (the linux program) to detect motion, and track the motion using pan and tilt. This allows me to fine tune the motion detection parameters, and filter out 'lightswitch' events (as `motion` calls them).
I can also trigger external events on motion detection.

My thought was to turn the camera motion detection sensitivity down (so it doesn't trigger on the light), and send a command via the API to trigger a motion event (like the external input trigger).

I can't figure how to do this via the API though. Is there a way to trigger `external event` or `motion` recording via the API?

Thanks.

**Comment by NickWaterton** [comment]
OK, figured out a method.

add this to `event.py`:
```
    def set_alarm_config(self, enable, channel=0):
        """
        Params:

        channel:
        video index, start from 0

        enable:
        +----------------------------+-----------------+-------------------+
        | ParamName                  | ParamValue type | Description       |
        +----------------------------+-----------------+-------------------+
        | Alarm[[channel].Enable     | bool            | true/false        |
        +----------------------------+-----------------+-------------------+

        enable format:
        <paramName>=<paramValue>[&<paramName>=<paramValue>...]
        """
        enable=str(enable).lower()
        if enable == "true" or enable == "false":
            ret = self.command(
                'configManager.cgi?action=setConfig&Alarm[{0}].Enable={1}'.format(channel, enable)
            )
            if "ok" in ret.content.decode('utf-8').lower():
                return True

        return False
```
Now, you set 'Event' 'Alarm" to `disabled`, but enable 'Alarm recording' sensor type NC, anti-dither 60, record delay 10. in the camera configuration.

From python, you can now trigger a recording event using `camera.set_alarm_config(True)`, you then set `camera.set_alarm_config(False)` and the camera will record 70 seconds of video (or whatever you have anti-dither plus camera delay set to).

The timing starts from when you set `camera.set_alarm_config(False)`

If you don't set `camera.set_alarm_config(False)` the camera just keeps recording until you do.

The files recorded via this method can be distinguished from other files as they are marked `[A]` as opposed to `[R]` or `[M]`.

Hope you find this useful.

**Comment by pnbruckner** [comment]
I would say, yes, the above technique would work, if your camera happens to have an alarm input. Not all do. (E.g., only one of the three I own have an alarm input.)

But I have to ask, if you're recording 24/7, why do you need to trigger a "motion" or "alarm" based recording as well?

**Comment by NickWaterton** [comment]
There are various ways to trigger a motion event, this is just one, you can do the same with other triggers (if you have them), it works with motion if you have the sensitivity set high.

The reason for this is that all recordings are marked as "scheduled" unless there is an event of some kind, in which case a new recording is started marked "Alarm" or "Motion" etc. After the event, a new "Scheduled" recording starts. This allows you to easily see which are motion events (date, time and duration), and which are just scheduled. The scheduled ones are useful for seeing what happens before and after the Event, or if you know something happened, but there was no trigger.

This is useful as on the latest firmware, prerecord does not seem to work, so you only get recording from the instant the trigger occurs (not x seconds before).

**Comment by pnbruckner** [comment]
Ok, fair enough, and kind of what I expected the reason to be. Also, I suppose it would make retrieving an mp4 file for just the event easier.

So can we close this issue, or are you asking for something to be done (i.e., was it just a question that has been answered, or is this a feature request)?

**Comment by NickWaterton** [comment]
I sor of asked and answered my own question, so we can close it
