### ISSUE TITLE
AttributeError: module 'socket' has no attribute 'TCP_KEEPIDLE'

### ISSUE THREAD

**Issue by rtmgllc** [tchellomello/python-amcrest#152]
Getting the following error when I try to run anything, even just getting cam info: 

AttributeError: module 'socket' has no attribute 'TCP_KEEPIDLE'

Process finished with exit code 1

**Comment by pnbruckner** [comment]
What OS are you running this on and what version of Python are you using? It seems not all configurations support `TCP_KEEP*`.

**Comment by rtmgllc** [comment]
This would be on OSX and Python 3.8.0

**Comment by pnbruckner** [comment]
So that code was added to get the `event_stream` and `event_actions` methods to work, and mainly for use by Home Assistant. Without keep alive it had issues. I suppose it might be possible to not use keep alive if the system doesn't support `TCP_KEEP*`, but I'm not sure what the effect would be on event streaming. But at least that would allow other things to continue to work.

Can you try commenting out the related code in `http.py` and let me know how it works for you?

**Comment by rtmgllc** [comment]
No problem, I will try tonight and let you know.

**Comment by pnbruckner** [comment]
At least do this:
```python
_KEEPALIVE_OPTS = HTTPConnection.default_socket_options + [
    (socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1),
#    (socket.IPPROTO_TCP, socket.TCP_KEEPIDLE, KEEPALIVE_IDLE),
#    (socket.IPPROTO_TCP, socket.TCP_KEEPINTVL, KEEPALIVE_INTERVAL),
#    (socket.IPPROTO_TCP, socket.TCP_KEEPCNT, KEEPALIVE_COUNT),
]
```
That should at least enable keep alive, although the default of 2 hours may not be useful here.

**Comment by rtmgllc** [comment]
I commented out the lines and it works.

**Comment by pnbruckner** [comment]
After making that change did you try using `event_stream` or `event_actions`? If not, can you? If you have, did they work?

**Comment by rtmgllc** [comment]
Trying now....

**Comment by rtmgllc** [comment]
Something like this I assume? 

`    from amcrest import AmcrestCamera
    camera = AmcrestCamera('192.168.0.1', 80, 'admin', 'password').camera
camera.realtime_stream(path_file="/home/user/Desktop/myvideo")`

**Comment by rtmgllc** [comment]
This is what I now get: 

`<AMC001SW_6Y22GA:AMC001SW1QP46Y22GA> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://10.0.0.60:80/cgi-bin/realmonitor.cgi?action=getStream&channel=1&subtype=0')
<AMC001SW_6Y22GA:AMC001SW1QP46Y22GA> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://10.0.0.60:80/cgi-bin/realmonitor.cgi?action=getStream&channel=1&subtype=0')
<AMC001SW_6Y22GA:AMC001SW1QP46Y22GA> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://10.0.0.60:80/cgi-bin/realmonitor.cgi?action=getStream&channel=1&subtype=0')
Traceback (most recent call last):
  File "/Users/jared/.pyenv/versions/3.8.0/lib/python3.8/site-packages/amcrest/http.py", line 198, in _command
    resp.raise_for_status()
  File "/Users/jared/.pyenv/versions/3.8.0/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://10.0.0.60:80/cgi-bin/realmonitor.cgi?action=getStream&channel=1&subtype=0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stream.py", line 20, in <module>
    camera.realtime_stream(path_file="/Users/jared/Desktop/myvideo")
  File "/Users/jared/.pyenv/versions/3.8.0/lib/python3.8/site-packages/amcrest/special.py", line 32, in realtime_stream
    ret = self.command(
  File "/Users/jared/.pyenv/versions/3.8.0/lib/python3.8/site-packages/amcrest/http.py", line 163, in command
    return self._command(*args, **kwargs)
  File "/Users/jared/.pyenv/versions/3.8.0/lib/python3.8/site-packages/amcrest/http.py", line 203, in _command
    raise CommError(error)
amcrest.exceptions.CommError: 400 Client Error: Bad Request for url: http://10.0.0.60:80/cgi-bin/realmonitor.cgi?action=getStream&channel=1&subtype=0`

**Comment by pnbruckner** [comment]
Close, but:
```python
from amcrest import AmcrestCamera
camera = AmcrestCamera('192.168.0.1', 80, 'admin', 'password', timeout_protocol=6.05).camera
camera.event_actions("Video_motion", retries=5)
```

**Comment by rtmgllc** [comment]
Ah, trying again now...

**Comment by rtmgllc** [comment]
> Traceback (most recent call last):
  File "eventactions.py", line 3, in <module>
    camera.event_actions("VideoMotion", retries=5)
AttributeError: 'Http' object has no attribute 'event_actions'

**Comment by rtmgllc** [comment]
`Traceback (most recent call last):
  File "eventactions.py", line 3, in <module>
    camera.event_actions("VideoMotion", retries=5)
AttributeError: 'Http' object has no attribute 'event_actions'`

**Comment by pnbruckner** [comment]
What version have you installed? You need to use the latest (1.7.0) and modify that.

**Comment by rtmgllc** [comment]
I did a git clone yesterday, so I assume its the newest.

**Comment by rtmgllc** [comment]
Oh wait, I lied, pip shows 1.6.0! I will upgrade and try again. My bad.

**Comment by rtmgllc** [comment]
No longer getting errors. What does `camera.event_stream("VideoMotion", retries=5)` do? Does it modify a config on the camera?

**Comment by rtmgllc** [comment]
Ok, it works. I get (5) pictures triggered from motion detection. 

I guess the other issue is the streaming video, I get the error I posted a few posts back. Is that supposed to record a video file somewhere? Maybe its not for my camera model? (IPM-721)

**Comment by pnbruckner** [comment]
>  I get (5) pictures triggered from motion detection.

It's good you're not getting errors anymore. I'll try to release a new version that deals with `socket.TCP_KEEP*` not existing.

FWIW, the `event_stream` & `event_actions` methods return a generator. To see if they are _really_ working for you, try this (which is what I should have suggested originally):
```python
from amcrest import AmcrestCamera
camera = AmcrestCamera('192.168.0.1', 80, 'admin', 'password', timeout_protocol=6.05).camera
for code, start in camera.event_actions("VideoMotion", retries=5):
    print(code, start)
```
That should output lines that look like this (as motion is detected and not):
```
VideoMotion True
VideoMotion False
```
That should run forever. (Hit Ctrl-C to escape out of the loop.) If you could try that and let me know how it does, that would be appreciated.

**Comment by rtmgllc** [comment]
It works, I get the output you mentioned. Thanks! 

I am going to work on having the cameras move to certain positions based on time of day using the scripts.
