### ISSUE TITLE
Release 1.8.0?

### ISSUE THREAD

**Issue by flacjacket** [tchellomello/python-amcrest#180]
It'd be great to have a new release now that some of the NVR channel related functionality is in. Looking at the commits since 1.7.2, I think this is the set of key changes:

Breaking changes
* Python 2 no longer supported, Python 3.6 is the minimum required version
* PTZ commands (e.g. `zoom_in`, `move_left`) require boolean value for `start` parameter, rather than `"start"` and `"stop"` strings for the `action` parameter

New features
* Smart motion detection events added as `is_human_detected` and `is_vehicle_detected` properties.
* Added methods to query separate channels to allow using multiple cameras on NVRs.
* Type annotations added to allow for type checking.

I'd say no particular rush to get this out, just curious what sort of things would be needed to get to the point of cutting a release. A couple of the current open PRs seem like they are also close to ready if they can get some minor fixes from authors, so those would probably be good to get in if possible.

**Comment by tchellomello** [comment]
@flacjacket++ you are more than welcome to start a new release review and I give me your username on pypi that I'll grant you permission to publish a new package.  Thanks for all your work!

**Comment by flacjacket** [comment]
Great, just created a PR for it. My pypi username is `svig`. Thanks!

I just noticed, this is even issue `180`, haha.

**Comment by flacjacket** [comment]
@tchellomello I added the source and wheel packages to the 1.8.0 release. You can upload to pypi, and I'd be happy to as well if you add me to the pypi project. Thanks!

**Comment by tchellomello** [comment]
> @tchellomello I added the source and wheel packages to the 1.8.0 release. You can upload to pypi, and I'd be happy to as well if you add me to the pypi project. Thanks!

@flacjacket let me know your `pypi` username and I'll be happy to grant you access! Thanks

**Comment by flacjacket** [comment]
> > @tchellomello I added the source and wheel packages to the 1.8.0 release. You can upload to pypi, and I'd be happy to as well if you add me to the pypi project. Thanks!
> 
> @flacjacket let me know your `pypi` username and I'll be happy to grant you access! Thanks

Yeah, it is `svig`
