### ISSUE TITLE
Permission denied on  git@github.com:tchellomello/python-amcrest.git

### ISSUE THREAD

**Issue by laurenweinstein1** [tchellomello/python-amcrest#185]
Hi. Getting:

git clone git@github.com:tchellomello/python-amcrest.git

Permission denied (publickey).
fatal: Could not read from remote repository.

Any clues? Thanks.

**Comment by simcop2387** [comment]
github does not recognize your ssh key, add it to your account profile

**Comment by pjrt** [comment]
https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account

**Comment by flacjacket** [comment]
This is a general github question, and should be handled with the docs from @pjrt.
