### ISSUE TITLE
Ability to set default timeout for all commands

### ISSUE THREAD

**Issue by colinodell** [tchellomello/python-amcrest#23]
Right now, it looks like `scan_devices()` might be the only function where you can pass in a custom timeout.  In other cases, such as `snapshot()`, there's no way to override the default timeout of 3 seconds.

**Comment by dougsland** [comment]
My first attempt tonight: https://github.com/tchellomello/python-amcrest/pull/26

**Comment by tchellomello** [comment]
Implemented on #26.

**Comment by dougsland** [comment]
@colinodell 
I believe this new PR (bellow) should cover this request, please let us know in case it's still missing something:
https://github.com/tchellomello/python-amcrest/pull/28

Also, fell free to comment before we merge patches. Thanks!
