### ISSUE TITLE
remove python2 support in the spec

### ISSUE THREAD

**Issue by dougsland** [tchellomello/python-amcrest#50]
HomeAssistant is python3, TUI is python3 only, most of distros now support python3 from a long time.

**Comment by jimboca** [comment]
Please keep Python 2 supported.

**Comment by dougsland** [comment]
@jimboca sure, let's keep it. What's your use case of lib? So we can always keep it in mind. Thanks!

**Comment by jimboca** [comment]
Thanks! I plan to add it to https://github.com/jimboca/camera-polyglot to support these cameras with the UDI ISY994 controller.

**Comment by dougsland** [comment]
@jimboca we will work in the backport of TUI to python2, in case you need it. (No xwindow scenario)

**Comment by tchellomello** [comment]
Should we close this issue?
