### ISSUE TITLE
Post Audio Stream (Enhancement)

### ISSUE THREAD

**Issue by d-adamson** [tchellomello/python-amcrest#59]
Nice project. Thanks!
Could you implement the Post Audio Stream API (ref section 4.3.3 in the API manual 2.10 2016-05-25)?

Use case:
When motion or sound are detected, play an audio file over the camera's speaker to act as a deterrent. Examples: dog barking, TV or radio playing, background conversations, alarm sound, etc.

**Comment by tchellomello** [comment]
Hello @d-adamson  that is a great idea!!

**Comment by d-adamson** [comment]
Inspired from the Home Alone movie 😃

David Adamson

**Comment by d-adamson** [comment]
I've played around with this a little. Here is a code snippet using the curl program from the command line in Linux. Substituting your user name, password and IP address (of course). 
Hopefully this will be of some help to the next person.

The AMCREST seems to be pretty particular about the wav file format. After some trial and error the following worked. Still have not been able to successfully convert  & play an mp3 file :(  
$ ffmpeg -i 9000g.wav -acodec pcm_alaw -ar 8000 9000g_pcm.wav

$ curl -verbose   --request POST   --url 'http://admin:yourpassword@192.168.1.xxx/cgi-bin/audio.cgi?action=postAudio&httptype=singlepart&channel=1'   --header 'content-length: 9999999'   --header 'content-type: Audio/G.711A'   --data-binary @9000g_PCM.wav

[9000g.zip](https://github.com/tchellomello/python-amcrest/files/853465/9000g.zip)

**Comment by dougsland** [comment]
Thanks for your collaboration Adam, really motivated me to step out and provide a patch soon.

**Comment by dougsland** [comment]
https://github.com/tchellomello/python-amcrest/pull/63
