### ISSUE TITLE
No package called "fbida"

### ISSUE THREAD

**Issue by Cabalist** [tchellomello/python-amcrest#64]
There is currently nothing in pypi called `fbida` and the top google results point back to this repo.  What is `fbida`?

**Comment by tchellomello** [comment]
Hello @Cabalist, yes that is correct. That is a bug. 

We are working on the PR https://github.com/tchellomello/python-amcrest/pull/61 that will address this issue. 

Thanks for reporting this issue.

**Comment by dougsland** [comment]
@Cabalist fbida is the package for fbi - Linux framebuffer imageviewer

**Comment by tchellomello** [comment]
@Cabalist  fixed

**Comment by Cabalist** [comment]
Thanks.  I didn't see the unittest branch at the time.
