### ISSUE TITLE
Latest firmware update requires Digest auth, breaks HTTP basic auth requests

### ISSUE THREAD

**Issue by dparker18** [tchellomello/python-amcrest#70]
I'm working with a IP2M-841, just upgraded to new firmware V2.420.AC00.17.R 3/22/17

After upgrading, all my third party tools and custom code using python-amcrest broke on any request:

```
Traceback (most recent call last):
  File "/home/homeassistant/DPtest.py", line 7, in <module>
    print(c.camera.current_time)
  File "/home/homeassistant/.homeassistant/deps/amcrest/system.py", line 19, in current_time
    'global.cgi?action=getCurrentTime'
  File "/home/homeassistant/.homeassistant/deps/amcrest/http.py", line 102, in command
    resp.raise_for_status()
  File "/home/homeassistant/.homeassistant/deps/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://xyz.xyz.xyz.xyz:80/cgi-bin/global.cgi?action=getCurrentTime
```

I verified by tcpdump/wireshark that we're sending basic auth in the request, and the camera responds 401 and asks for digest auth.

Seems others are seeing it too:
https://amcrest.com/forum/technical-discussion-f3/cgi-sdk-no-longer-functioning-on-17r--t2401.html

I fixed it by changing to digest auth in http.py:
`self._token = requests.auth.HTTPDigestAuth(self._user, self._password)`

Everything is working now, happy to submit a PR

**Comment by tchellomello** [comment]
Hello @dparker18, thank you reporting this issue. 
You PR is very welcome. Make sure to keep the compatibility across the older versions too on your PR. 
We will be happy to merge your contribution. :+1:
