### ISSUE TITLE
Tested/Working with IP3M-941

### ISSUE THREAD

**Issue by ChadCurvin** [tchellomello/python-amcrest#83]
Tested and appears to be working with Amcrest IP3M-941 ( https://smile.amazon.com/Amcrest-UltraHD-Security-3-Megapixel-IP3M-941W/dp/B01M0IHF9K ). Feel free to update the Matrix :)

Thanks for the hard work!!

**Comment by tchellomello** [comment]
@ChadCurvin thanks for your feedback. Do you want to submit a PR and update the docs yourself? 

Please feel free to submit a PR and we will be happy to merge it.

**Comment by dougsland** [comment]
Thanks @ChadCurvin we updated the table, appreciate your help! 
https://github.com/tchellomello/python-amcrest/pull/84
