### ISSUE TITLE
Relay input/output

### ISSUE THREAD

**Issue by mikegeeezy** [tchellomello/python-amcrest#90]
I've got a couple of Amcrest IP2M-841W camera's setup at the house.  I made a kludge smoke detector for one that feeds into the camera relay, using a DC-DC step up converter to get the 9v required by the sensor.

It works OK and the app on my phone pushes me a notification if the relay is triggered.  But it's not really enough to wake me up or alert the whole house etc.  It would be great if I could have those relays exposed to homeassisstant.  I'm not a software developer and don't have a sense for what it would take to get them working.  Just wanted to post here and see if there's any interest.

![image](https://user-images.githubusercontent.com/26230753/34452202-707ecbe8-ed3a-11e7-8541-e7ecd53b614f.png)

**Comment by dougsland** [comment]
@mikegeeezy did you try to use our python module directly? Marcelo created the integration with HA. @tchellomello could you please check how to integrate with HA?

**Comment by tchellomello** [comment]
@mikegeeezy I think the best route is to connect your smoke detector using a raspberry pi with an arest sensor. 

@mikegeeezy ask that on the HA forums as people might have some nice input.
