### ISSUE TITLE
Amcrest IP8M-2496EB partially working...  !

### ISSUE THREAD

**Issue by TEfjLONjDON** [tchellomello/python-amcrest#99]
Using Hassio component Amcrest IP Camera with "camera platform amcrest" & "sensor platform amcrest" for my "IP8M-2496EB for 1 month now. 

Camera is displayed perfectly after setting to (resolution) low. I use the RSTP method and I'm curious if that could be the cause of my issue.   (The sensor and switch errors below mention the HTTP transport protocol. Are they not to be used with RSTP

"Sensor" and "Switch" through a time out errors ever 2 seconds.  Logs fill fast.  But the associatied entities appear to be functioning correctly. (ie.. they yeld "state / data" that changes accurately.)

See details below. 
`   Log Details (WARNING)
Fri Dec 21 2018 04:35:51 GMT-0500 (Eastern Standard Time)

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPConnectionPool(host='192.168.***.***', port=**): Read timed out. (read timeout=3.0)",)': /cgi-bin/magicBox.cgi?action=getSoftwareVersion `

I will adjust the scan itnerval. But I suspect this time out issue is related to setting in amcrest.py component used by hassio. Any help would be most appreciated.

I also get this error.. 

`Log Details (WARNING)
Fri Dec 21 2018 04:30:21 GMT-0500 (Eastern Standard Time)

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x6f448930>, 'Connection to 192.168.***.*** timed out. (connect timeout=3.0)')': /cgi-bin/configManager.cgi?action=getConfig&name=MotionDetect  `

Obviously I redacted my internal IP of the camera...

**Comment by tchellomello** [comment]
@TEfjLONjDON  thanks your report. During my tests it feels like the webserver running in the cameras are not handling the requests and it times out. For some other models, I don't have this problem. It seems to be a firmware problem. 
Please let us know if any tweak helped to address the problem.

**Comment by TEfjLONjDON** [comment]
At present I have the "scan interval:" , "sensors:" & "switches" commented out using a hashtag at the start of each line I desire to ommit {example ..(#   -blablabla:. )}
I've also added an additional IP8M-2496EB camera for a total of two cameras using the amcrest platform in HASSIO since our last communication.

**Comment by ziptbm** [comment]
I'm seeing the same type of errors repeatedly with the IP3M-HX2's on firmware 2.520.AC00.18.R, Build Date: 2017-06-29.  I have 4 of these cameras in my setup and I get Retrying errors every few seconds.  

The errors all look the same, but appear to be for "getSoftwareVersion", "getDeviceAllInfo", "getSerialNo" , etc. at the end of the error.

@TEfjLONjDON - did you find a specific configuration that prevents the errors?

@tchellomello - I reported [this similar issue under the main Home Assistant page](https://github.com/home-assistant/home-assistant/issues/19687).  Do you think this is firmware related as well?  This is the latest and shipped in mid-2017.   Please let me know what else would be helpful.

**Comment by pnbruckner** [comment]
These issues should be addressed in the 1.5.5 release, which should hopefully be used by HA shortly.
